# search parameters
SEARCH_MAX_RESULTS = 3
TEMPERATURE = 0.0
SEED = 1234
USE_TEXT_SEARCH = "hybrid"
USE_VECTOR_SEARCH = "hybrid"
USE_SEMANTIC_RANKER = False
USE_SEMANTIC_CAPTIONS = False
MINIMUM_SEARCH_SCORE = 0.0
MINIMUM_RERANKER_SCORE = 0.0

# answer generation parameters
CHAT_RESPONSE_MAX_TOKENS = 512